# Generated by Django 4.2.13 on 2025-11-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='compartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compartments.compartment'),
            preserve_default=False,
        ),
    ]
