# Generated by Django 5.0.6 on 2025-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0007_rename_expires_at_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_penalty_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='no_show_count',
            field=models.IntegerField(default=0),
        ),
    ]
