# Generated by Django 4.2.25 on 2025-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0008_student_is_restricted_student_last_penalty_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['student'], name='compartment_student_0698c1_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code'], name='compartment_code_bbeafc_idx'),
        ),
    ]
