# Generated by Django 4.2.25 on 2025-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0009_otp_compartment_student_0698c1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fines',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding fines in rupees', max_digits=10),
        ),
    ]
