# Generated by Django 5.0.6 on 2025-09-23 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_booking_duration', models.IntegerField(default=180, help_text='Maximum booking duration in minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(720)])),
                ('max_advance_booking_days', models.IntegerField(default=1, help_text='Maximum days in advance a booking can be made', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('check_in_buffer', models.IntegerField(default=15, help_text='Minutes allowed for check-in after reservation start', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('max_active_reservations', models.IntegerField(default=1, help_text='Maximum number of active reservations per user', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('penalty_threshold', models.IntegerField(default=3, help_text='Number of no-shows before penalties apply')),
                ('penalty_duration_days', models.IntegerField(default=7, help_text='Number of days user is restricted after exceeding threshold')),
            ],
            options={
                'verbose_name_plural': 'Library Settings',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Checked In', 'Checked In'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No Show', 'No Show')], default='Reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.seat')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_show_count', models.IntegerField(default=0)),
                ('last_penalty_date', models.DateTimeField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
