# Generated by Django 5.0.6 on 2025-09-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0008_student_is_restricted_student_last_penalty_date_and_more'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compartments.student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
