# Generated by Django 5.0.6 on 2025-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_user_reservation_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked In', 'Checked In'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No Show', 'No Show')], default='Reserved', max_length=20),
        ),
    ]
