# Generated by Django 4.2.25 on 2025-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['student'], name='reservation_student_1c05a6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['seat'], name='reservation_seat_id_761526_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time'], name='reservation_start_t_f3e5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['end_time'], name='reservation_end_tim_c11544_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['student', 'status', 'end_time'], name='reservation_student_be6772_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['is_active'], name='reservation_is_acti_d55564_idx'),
        ),
    ]
