# Generated by Django 4.2.25 on 2025-10-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_reservation_student_1c05a6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked In', 'Checked In'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No Show', 'No Show')], default='reserved', max_length=20),
        ),
    ]
