# Generated by Django 4.2.25 on 2025-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'reserved'), ('checked_in', 'checked_in'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('no_show', 'no_show')], default='reserved', max_length=20),
        ),
    ]
